<?php
require_once("../lib/config.php");
?><!doctype html>
<html>
<head>
    <title>Play Button: Auto Generated</title>
</head>
<body>
    <?php
            // Get the metatune instance. 
            $spotify = MetaTune::getInstance();
            $spotify->autoAddTracksToPlayButton = true; // Will add all searches for tracks into a list.
            $spotify->playButtonHeight = 330; // For viewing the entire playlist
            $spotify->playButtonTheme = "white"; // Changing theme
            $spotify->playButtonView = "list"; // Changing view
            try
            {
                $tracks = array(
                    $spotify->lookup("spotify:track:4kO7mrAPfqIrsKwUOK5BFx"),
                    $spotify->lookup("spotify:track:0n49fCjNGsbtNOE6cuWk79"),
                    $spotify->lookup("spotify:track:5kQ7CU798Sqm1BWNbYHFMa"),
                    $spotify->lookup("spotify:track:57Xjny5yNzAcsxnusKmAfA")
                );

                echo $spotify->getPlayButtonAutoGenerated("My favorites");
            }
            catch (MetaTuneException $ex)
            {
                die("<pre>Error\n" . $ex . "</pre>");
            }

    ?>
</body>
</html>